### ISSUE TITLE
MPQ Protect NEW SAE

### ISSUE THREAD

**Issue by SasukeMV** [ladislav-zezula/StormLib#117]
Good evening, I would like to inform you about a new PROTECT which does not work MPQ W3x scaner and are not looking for files, and finds a dummy. So.

![image](https://user-images.githubusercontent.com/32784461/31571151-19f50926-b096-11e7-89c3-5d50eacfd789.png)

So the same Block size Hash table 200 all on one line. 

Please understand and do something to the map in MPQ editor worked fine.

![image](https://user-images.githubusercontent.com/32784461/31571165-4d16871c-b096-11e7-8974-42722227954a.png)

Everything above this line is dummy only.

Everything below is the files you need, but if you separate them rudely, the file integrity is lost.

![image](https://user-images.githubusercontent.com/32784461/31571175-9944d602-b096-11e7-9026-a133777afb45.png)

**Comment by SasukeMV** [comment]
https://drive.google.com/file/d/0B1eRhl7ayVfbWVloZmE2WE1UX1k/view?usp=sharing

**Comment by ladislav-zezula** [comment]
Hi,

 

it actually works and does detect something. The names in the MPQ

contain non-printable characters, that’s why you can’t see anything useful

in the detected list. See the attachment.

 

There is nothing to fix.

 

L.

**Comment by Unryze** [comment]
Let me restate what Sasuke meant, (he used google translate) that is why it is very unclear what he meant.

You have added "deep file verification", however it does not work with these particular maps, as it believe that the data exists, even when it does not. 
![deepfileverification](https://user-images.githubusercontent.com/11413837/31586024-767873ee-b1dc-11e7-94ac-f96466a6ae64.jpg)
So, after I use this option or even without it I get this:
![filescan15141files](https://user-images.githubusercontent.com/11413837/31586027-809364c4-b1dc-11e7-95e2-8704f49673a2.jpg)
This map does not contain even close to 15141 files, most of them are dummy or are being read incorrectly by MPQ Editor. Which you can see here:
![wrongfiles1](https://user-images.githubusercontent.com/11413837/31586083-598717b2-b1dd-11e7-9de9-fe623e306729.jpg)
Then we take a look at files that are 999+mb like this:
![wrongfiles2](https://user-images.githubusercontent.com/11413837/31586088-637e06a4-b1dd-11e7-8677-a29917041a06.jpg)
And if we try extracting some files (that are not supposed to be here) we get this error:
![errornotexistingfile](https://user-images.githubusercontent.com/11413837/31586105-7362b47a-b1dd-11e7-90ba-a161fcc361c3.jpg)
Hopefully this explains the situation. Should have reported this myself... was a bit lazy, sorry.

With regards,
Sandro Takaishvili.

**Comment by ladislav-zezula** [comment]
Hi,

 

I see the problem. The MPQ does contain many dummy files that

are absurdly big, without actually containing anything. This is, by design

of MPQ format, allowed – the entry in the block table may contain

offset to a non-compressed file pointing anywhere within the MPQ.

 

I changed Deep File Verification a bit. When turned on, MPQEditor

will attempt to read end of the file (last 16 bytes, assumed the file size

is bigger than 16 bytes). If it fails, the file is not included.

 

This is not 100% cure for the problem. If the file starts within the MPQ

and also ends within the MPQ, the only way is to check the actual file

data. But that’s beyond the scope of MPQ Editor and I leave that

for the people who work with the files.

 

At least those 900MB files are gone.

 

L.

**Comment by ladislav-zezula** [comment]
I see. The MPQ does contain many dummy files that are absurdly big, without actually containing anything. This is, by design of MPQ format, allowed – the entry in the block table may contain offset to a non-compressed file pointing anywhere within the MPQ.

I improved Deep File Verification a bit. It verifies file end instead of file begin, and some more.

This is not 100% cure for the problem. If a file starts within the MPQ and also ends within the MPQ, the only way is to check the actual file data (i.e. if it's a file.blp, it must be a BLP file. But that only works when we actually know the name. 

At least those 900MB dummy files are gone.

**Comment by Unryze** [comment]
As per usual, thank you very much, you never cease to amaze me. o/

**Comment by Unryze** [comment]
One last bump, updated some info, hope it proves itself useful. Sorry for the double post, just making sure you see it.

And hopefully this will be the last time you will be annoyed with WC3 related stuff.

Much appreciated,
Sandro Takaishvili.

**Comment by ladislav-zezula** [comment]
> Is it possible to make Deep File verification ignore files that begin with 08 00 00 00 ?

Sure it is. But if I do that, next week I get map where all files will start with 09 00 00 00. BTW, Have you tried the Live Name Scanner? That one actually watches Warcraft III what it's doing and will catch all names that are being open and logs it to a file. Go for it, save a new listfile and discard your own one (the listfile). That should be far more accurate than any hackery - because at some point, the game MUST read the file and it will only read files that are actually there.

**Comment by Unryze** [comment]
I see, the problem with that is, it does not detect the files that were not loaded in (like some models that are not present, textures, etc,)

I have another suggestion, but you might not like it. Add arguments to deep file scan, so it is possible to add hex values to skip (aka add what to skip additionally).

But I do understand what you mean, in case my suggestion is bad, then I don't know, because to be fair it is only needed once, I myself am tired from WC3, so even if they do update it I will no longer bother you with it.

Thank you.

**Comment by ladislav-zezula** [comment]
> I have another suggestion, but you might not like it. Add arguments to deep file scan,

That would not help either. Understand, the map protector could set the beginning of the dummy files to ANY offset within the MPQ, as long as (offset+size) doesn't cross the end of the file.

**Comment by Unryze** [comment]
Well, if there is a way to add the hex data to ignore yourself in the files, then that actually would fix the problem, at least for those who will look it up, like me. But I don't know if it is possible to make it as easy as it sounds.

Ah, you meant that the 08 00 00 00 or any other data can be hidden in any other place, I see. But can you update it one last time with this added? You will not need to do it again, as even if there will be anything newer that uses same principle you should just ignore it.

As currently that is the last thing that is "protecting" files thus far. 

Sorry for the inconvenience,
Sandro Takaishvili.

**Comment by ladislav-zezula** [comment]
One-time build:
http://www.zezula.net/download/mpqediten32_08000000.zip
