### ISSUE TITLE
Can't count files

### ISSUE THREAD

**Issue by juvian** [ladislav-zezula/StormLib#130]
Hi, I have this code:
	
int files = 0;

	if (SFileOpenArchive(_T("Eden_RPG_S2_3.1C.w3x"), 0, 0, &hM)) {
		if (GetLastError() == ERROR_SUCCESS) {
			hFile = SFileFindFirstFile(hM, "*", &data, NULL);
			while (SFileFindNextFile(hFile, &data)) {
				files++;
			}
			std::cout << files << " files \n";
		}
	}
    
	nError = GetLastError();
       if(nError != ERROR_SUCCESS)  printf("errror %d", nError);

which works fine for "normal" w3 maps, but not for "protected" ones.  How does MPQ Editor work and this not?

**Comment by ladislav-zezula** [comment]
Re: [ladislav-zezula/StormLib] Can't count files (#130)


Hi,

try to open each one. Protected maps are crap, they
contain lots of bogus entries in the hash tables.

L.





Hi, I have this code:
int files = 0;

if (SFileOpenArchive(_T("Eden_RPG_S2_3.1C.w3x"), 0, 0, &hM)) {
 if (GetLastError() == ERROR_SUCCESS) {
  hFile = SFileFindFirstFile(hM, "*", &data, NULL);
  while (SFileFindNextFile(hFile, &data)) {
   files++;
  }
  std::cout << files << " files \n";
 }
}

nError = GetLastError();
   if(nError != ERROR_SUCCESS)  printf("errror %d", nError);
which works fine for "normal" w3 maps, but not for "protected" ones. How does MPQ Editor work and this not?
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.





--
S pozdravem,
 Ladislav Zezula
 mailto:zezula@volny.cz

**Comment by juvian** [comment]
Well, map does not have listfile, so just wanted a method to iterate all its files.  For protected map, SFileOpenArchive return true but GetLastError() gives 1392

**Comment by ladislav-zezula** [comment]
> SFileOpenArchive return true but GetLastError() gives 1392

Only check LastError when a function returns `false`. Otherwise, GetLastError usually returns whatever was there before.

**Comment by juvian** [comment]
Yeah my bad, SFileOpenArchive gives 1392 error, but MPQ Editor opens it fine

**Comment by juvian** [comment]
I still don't understand how MPQ Editor can open it but stormLib can't
