### ISSUE TITLE
Stormlib opens the wrong file.

### ISSUE THREAD

**Issue by actboy168** [ladislav-zezula/StormLib#133]
Hi, someone reported a bug to me. It looks like stormlib supports a special file name, such as file00000001.blp. When a normal file name is exactly the same as it is, Stormlib considers it to be another file.
This is a map that can be reproduced. file00000002.blp should be a blp file, but stormlib thinks it is war3map.wtg.

[icon_error.zip](https://github.com/ladislav-zezula/StormLib/files/2090162/icon_error.zip)

**Comment by ladislav-zezula** [comment]
The opening by special name is there if you don;t know the name. But yeah, because MPQ Editor shows that special name in the form of file########.ext, then sooner or later, someone had to add a file under that name.

I changed that behavior so that StormLib first checks whether the file name exists (no matter what file name is it). If it fails, then it looks for a file index.

Fixed in commit 4ad0bff21da0163917e1552960e6a43679586b89.
