### ISSUE TITLE
SFileReadFile fails with 1004 (ERROR_FILE_CORRUPT) in this mpq archive, but the file is not corrupt?

### ISSUE THREAD

**Issue by claggers** [ladislav-zezula/StormLib#237]
Hi,

I have a starcraft 1 map which I think has been protected in some way. The map works fine in game so I believe the archive is not actually corrupt and that this is some intentional map protection.

the archive is here: [https://bounding.net/api/maps/80b9861d26fe36b4f81b79bb7faafeb1794e9d0f9adc27398a42954bc93713df/](https://bounding.net/api/maps/80b9861d26fe36b4f81b79bb7faafeb1794e9d0f9adc27398a42954bc93713df/)

I'm running version a5ef7a850aac844abf2e3859e26617ed596d4624 of stormlib. I built it for linux and I built some rust bindings for it, so I am calling all of this in rust but I don't think that affects anything here since MPQeditor behaves the same.

These are the two calls I'm doing:

```rust
bindings::SFileOpenFileEx(
                mpq_handle, 
                "staredit\\scenario.chk\0".as_ptr() as *mut _,
                0,
                &mut archive_file_handle as *mut _)
```

and

```rust
bindings::SFileReadFile(archive_file_handle, chk_data.as_mut_ptr() as *mut _, chk_data.len() as u32, &mut size as *mut _, 0 as *mut _)
```

the SFileReadFile fails (returns false) and GetLastError() shows 1004.

**Comment by ladislav-zezula** [comment]
Rename the file so what it has the `.scm` or `.scx` extension. Thats the only way how to let StormLib know that the MPQ is a Starcraft map.

Reason: This protector (fixed in https://github.com/ladislav-zezula/StormLib/pull/233) adds a fake `MPQ_FILE_SINGLE_UNIT (0x01000000)` flag to the block table. This flag indicates special way of encrypting file. However, Starcraft I doesn't know the flag so that it ignores it.

When StormLib detects that it's a Starcraft I map, it will ignore it too. But there's no other way to do it except the file extension.
![image](https://user-images.githubusercontent.com/3244359/147634866-61684e0c-78dc-4eff-a861-7dad6d62a38a.png)

**Comment by claggers** [comment]
Thank you, that did fix it. I think this archive also has two scenario.chk files. One with locale0 and one with locale1033. The locale0 one is mangled and fails to read with 1004, but locale1033 one can now be extracted.

**Comment by ladislav-zezula** [comment]
> One with locale0 and one with locale1033. The locale0 one is mangled and fails to read with 1004, but locale1033 one can now be extracted.

They (ab)use the fact that the game first looks at the file with that given locale, and if not there, it will take the file with neutral locale (0). A disadvantage if that is that non-English game versions will (probably) not be able to run.

**Comment by 3244542253** [comment]
@[ladislav-zezula]Hello,I recently encountered a problem: when I try to open StarCraft 1 map a protected by SMC 2.87 with scmdraft2, it will prompt that MPQ is protected. Then I open this map file a and extract chk file A. then I use scmdraft2 to create a new map file B, open them with hexeditor and copy the data in chk file a into chkb, Then use MPQ editor to replace the CHK files in the sub files B1 and B2 of map file B. when you open it with scmdraft, there are two different situations. When you open the new map file B1, the situation will be the same as a, but when you open the new map file B2, the situation will not be the same as a, There is no prompt "MPQ file is protected". Is this because of the encrypted password? Although I don't know what the password is, how can I use hexeditor to get relevant information in a hex area of chk file?

**Comment by ladislav-zezula** [comment]
No idea. Why don't you contact author of `scmdraft2`?
