### ISSUE TITLE
New MPQ protection 

### ISSUE THREAD

**Issue by GlitchLxrd** [ladislav-zezula/StormLib#262]
https://user-images.githubusercontent.com/65363348/192085232-0c542207-4be6-4fa4-aa06-557d80dd7b2d.mp4

https://user-images.githubusercontent.com/65363348/192085247-a9d5c15f-3491-4b4d-b54a-293aa092d33d.mp4

When i open https://drive.google.com/file/d/1tV84pQlae6jQT79sGsMZasduz66Qw95F/view , without listfile i can extract unkown files, but i the wc3 name scanner cant see any filename .
But if i open this .asi file with mpq i cant exctract any file . Because of error : File blablabla cant be found

**Comment by ladislav-zezula** [comment]
> But i the wc3 name scanner cant see any filename .

This is because the static name scanner expects a Warcraft III map. ASI files are not maps.

> But if i open this .asi file with mpq i cant exctract any file

I'll look why the file can't be open.

**Comment by ladislav-zezula** [comment]
I checked what's different in the MPQ. All files have Locale and Platform set to 0xFFFF (0xFF, respectively). StormLib never really support Platform other that 0. I slightly extended the `SFileSetLocale` API, so that it now accepts combination of `Locale` (16 bits) and `Platform` (8 bits). Also other functions that return file locale (such as `SFileFindFirstFile`) now return compound value of Locale + Platform.

The new version of StormLib is in the [LZ_LocaleAndPlatform](https://github.com/ladislav-zezula/StormLib/tree/LZ_LocaleAndPlatform) branch.

The new build of MPQ Editor reads the files just fine, but it's just in BETA:
http://zezula.net/download/mpqeditor_en_locale.zip
I'll remove the file when I eventually finish regression tests.

**Comment by ladislav-zezula** [comment]
I retested the whole library and it all went well. [New version of StormLib](https://github.com/ladislav-zezula/StormLib/releases/tag/v9.24) was released and [MPQ Editor](http://zezula.net/en/mpq/download.html) was rebuilt with this release.
