### ISSUE TITLE
Sprotect - Wc3 MPQ protection

### ISSUE THREAD

**Issue by Snipered** [ladislav-zezula/StormLib#78]
Hi. It's a "new"(maybe 3-4 month ago) hex protection by Koreans.
![ss 2016-06-18 at 09 23 17](https://cloud.githubusercontent.com/assets/1854678/16170587/144c780a-359b-11e6-9a94-cbe5fc963a78.png)
It's also changes locale of files to korean, so you can play maps under this protection only if play it on korean version of client.
Can't give you more details, because the only thing i know about it already written here.
[Maps.zip](https://github.com/ladislav-zezula/StormLib/files/321712/Maps.zip)

**Comment by Tailer007** [comment]
So what's the point of it, if it's easily read by MPQ Editor? Just extract all the files and put them into a dummy map, rebuild it and poof, you just ignored the "protection".

The question is, what do you expect Ladislav to do? As it's not even protected from MPQ Editor, but from wc3 itself? Making a MPQ rebuilder would be a hassle and it's impossible to be fair, as he will have to write the wc3 MPQ structure builder.

![123](https://cloud.githubusercontent.com/assets/11413837/16170619/a0b61dda-3561-11e6-8c75-baa75cfc42c9.jpg)

**Comment by Snipered** [comment]
Well, what version of MPQ Editor do you use? Since i can't open it.
![ss 2016-06-18 at 09 35 23](https://cloud.githubusercontent.com/assets/1854678/16170626/aa938654-359c-11e6-9b37-afebefc31e15.jpg)

**Comment by Tailer007** [comment]
Not even the latest version. 799 does the trick.
![mpqeditorversion](https://cloud.githubusercontent.com/assets/11413837/16170630/322940ee-3562-11e6-85a2-53241fe0e0ef.jpg)

**Comment by Snipered** [comment]
Uh... Well, tried to open it with x32 version of MPQ Editor(latest).
![ss 2016-06-18 at 10 01 41](https://cloud.githubusercontent.com/assets/1854678/16170733/6917d262-35a0-11e6-92d1-f962616cf39f.png)
x64 just crashes.

**Comment by Tailer007** [comment]
Dunno, works fine for me as you can see, also to get the files out you just need to apply listfile :)

**Comment by Snipered** [comment]
That's a problem. Because i'm using listfile.

**Comment by Tailer007** [comment]
Strange, can you make a screenshot of the version you use? As this crash problem was in a version before the latest commit.

**Comment by Snipered** [comment]
![ss 2016-06-18 at 10 54 53](https://cloud.githubusercontent.com/assets/1854678/16170987/bc053666-35a7-11e6-86e4-dd9cf6ec33e8.png)

**Comment by Tailer007** [comment]
Try the one that I'm using, and let's wait for Ladislav to read this ;)

[MpqEditor799.zip](https://github.com/ladislav-zezula/StormLib/files/321737/MpqEditor799.zip)

**Comment by Snipered** [comment]
Yeah, it's working, thanks. Let's wait.

**Comment by ladislav-zezula** [comment]
https://github.com/Snipered was right, it really did not work well with this map. Fixed in commit 303631f9d7f753dacffb1e038dd273dc204e1ea9.

The issue with this kind of protector is that they abuse the fact that the block index is added to block table pointer like this

pBlock = pBlockTable + pHash->dwBlockIndex

effectively doing this

pBlock = (LPBYTE)pBlockTable + (pHash->dwBlockIndex << 0x04)

During this operation, in 32-bit mode, the upper 4 bits of block table index get shifted away. Indexes like 0xF0000003 or 0x40000003 are treated as 0x0003. This is usually OK with 32-bit MPQ Editor and the game itself (there is no 64-bit Warcraft III), but makes huge problem in 64-bit MPQ Editor. The index gets added to the begin of the block table, going faaaaar away behind any buffer.

The above mentioned commit addresses this by masking the upper 4 bits from the block index.

**Comment by ladislav-zezula** [comment]
Keep them bad maps coming guys, maybe one day, MPQ Editor will be perfect and no protector will stand a chance.

**Comment by ladislav-zezula** [comment]
As for unknown names in Warcraft III Maps, here's little info:
http://www.zezula.net/en/mpq/war3maps.html
